// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repository;

#nullable disable

namespace Repository.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    partial class RepositoryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Entities.Models.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CustomerId");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("TelephoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("953a2bdc-7aab-46fa-9364-8858424ca7db"),
                            Address = "new address1",
                            Age = 25,
                            CreationDate = new DateTime(2022, 9, 13, 13, 26, 30, 274, DateTimeKind.Local).AddTicks(6844),
                            Email = "email@example.com",
                            LastName = "lastname1",
                            Name = "newbie",
                            TelephoneNumber = "111111111",
                            UserType = 0
                        },
                        new
                        {
                            Id = new Guid("5314362a-5f87-4b38-9a88-1174d5999cc5"),
                            Address = "new address1",
                            Age = 25,
                            CreationDate = new DateTime(2022, 9, 13, 13, 26, 30, 274, DateTimeKind.Local).AddTicks(6859),
                            Email = "email2@example.com",
                            LastName = "lastname1",
                            Name = "employee",
                            TelephoneNumber = "22222222",
                            UserType = 1
                        },
                        new
                        {
                            Id = new Guid("f6db198c-8780-4687-b5f6-9aa2530c65eb"),
                            Address = "new address1",
                            Age = 25,
                            CreationDate = new DateTime(2022, 9, 13, 13, 26, 30, 274, DateTimeKind.Local).AddTicks(6863),
                            Email = "email3@example.com",
                            LastName = "lastname1",
                            Name = "affiliate",
                            TelephoneNumber = "33333333",
                            UserType = 2
                        },
                        new
                        {
                            Id = new Guid("0d23ac2f-3a5d-466d-8cc6-f8f3dab296c7"),
                            Address = "new address1",
                            Age = 25,
                            CreationDate = new DateTime(2020, 9, 13, 13, 26, 30, 274, DateTimeKind.Local).AddTicks(6866),
                            Email = "email4@example.com",
                            LastName = "lastname1",
                            Name = "veteran",
                            TelephoneNumber = "33333333",
                            UserType = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
